apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: fake-ucore
  labels:
    project: athena
    app: fake-ucore
spec:
  selector:
    matchLabels:
      namespace: dev
      project: athena
      app: fake-ucore
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: dev
        project: athena
        app: fake-ucore
    spec:
      restartPolicy: Always
      containers:
        - name: fake-ucore
          image: mycluster-registry.localhost:5000/fake-ucore:latest
          ports:
            - name: http
              containerPort: 3000
            - name: metrics
              containerPort: 16670
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: fake-ucore-cfg
