apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: apolloconfig-server
  labels:
    project: athena
    app: apolloconfig-server
spec:
  selector:
    matchLabels:
      namespace: dev
      project: athena
      app: apolloconfig-server
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: dev
        project: athena
        app: apolloconfig-server
    spec:
      restartPolicy: Always
      containers:
        - name: apolloconfig-server
          image: minixxie/apollo-server-go:0.0.2
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config.json
              name: config-volume
              subPath: config.json
          imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: apolloconfig-server-cfg
