apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: llm-athena-api
spec:
  selector:
    namespace: dev
    project: athena
    app: llm-athena-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 16670
      targetPort: 16670