apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: apolloconfig-server
spec:
  selector:
    namespace: dev
    project: athena
    app: apolloconfig-server
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
