apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: consul-server
spec:
  selector:
    namespace: dev
    project: athena
    app: consul-server
  ports:
    - name: http
      protocol: TCP
      port: 8500
      targetPort: 8500
