apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: llm-athena-api
  labels:
    project: athena
    app: llm-athena-api
spec:
  selector:
    matchLabels:
      namespace: dev
      project: athena
      app: llm-athena-api
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: dev
        project: athena
        app: llm-athena-api
    spec:
      restartPolicy: Always
      containers:
        - name: llm-athena-api
          image: mycluster-registry.localhost:5000/llm-athena-api:latest
          ports:
            - name: http
              containerPort: 3000
            - name: metrics
              containerPort: 16670
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: llm-athena-api-cfg
