apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: llm-athena-svc
  labels:
    project: athena
    app: llm-athena-svc
spec:
  selector:
    matchLabels:
      namespace: dev
      project: athena
      app: llm-athena-svc
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        namespace: dev
        project: athena
        app: llm-athena-svc
    spec:
      restartPolicy: Always
      containers:
        - name: llm-athena-svc
          image: mycluster-registry.localhost:5000/llm-athena-svc:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          command: ["/bin/sh"]
          args:
            - -c
            - /app/app -consulHost=${consulHost} -consulPort=${consulPort} -consulToken=${consulToken} -apolloHost=${apolloHost} -apolloPort=${apolloPort}
          envFrom:
            - configMapRef:
                name: llm-athena-svc-cfg
