apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: llm-athena-svc
spec:
  selector:
    namespace: dev
    project: athena
    app: llm-athena-svc
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80